export type EventData = {
  id: string;
  slug: string;
  type: string;
  title: string;
  date: string;
  time: string;
  venue_name: string;
  venue_address: string;
  venue_map_url: string;
  maps_photo: string;
  main_image: string;
  person1_name: string;
  person1_role: string;
  person1_photo: string;
  person1_instagram: string;
  person2_name?: string;
  person2_role?: string;
  person2_photo?: string;
  person2_instagram?: string;
  gallery_photos: string[];
};
